project:
  type: website

website:
  title: "surpexample1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



