project:
  type: website
  output-dir: docs

website:
  title: "surpexample1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - about.qmd

format:
  html:
    theme: cosmos
    css: styles.css



